apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
data:
  MYSQL_PASSWORD: Q2xhcnVzd2F5XzE=
  MYSQL_ROOT_PASSWORD: UDEyMzQ1Ng==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-cm
data:
  MYSQL_DATABASE: phonebook
  MYSQL_DATABASE_HOST: mysql
  MYSQL_USER: clarus

  #! Created with kubectl create secret generic mysql-secret \
  #!  --from-literal=MYSQL_ROOT_PASSWORD=P123456 \
  #!  --from-literal=MYSQL_PASSWORD=Clarusway_1 --dry-run=client -o yaml > secret.yaml

  #? kubectl create configmap mysql-cm --from-literal=MYSQL_DATABASE=phonebook --from-literal=MYSQL_USER=clarus --from-literal=MYSQL_DATABASE_HOST=mysql --dry-run=client -o yaml > mysql-cm.yaml
