#! kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.1/deploy/static/provider/cloud/deploy.yaml
#! kubectl get svc -n ingress-nginx
#! curl 10.103.125.58/results to see content
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phonebook-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webserver
                port:
                  number: 80
          - path: /results
            pathType: Prefix
            backend:
              service:
                name: resultserver
                port:
                  number: 80
