apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-server
  template:
    metadata:
      labels:
        app: result-server
    spec:
      containers:
        - name: result-server
          image: burhanycl/result_project206
          # image: {{ .Values.resultserver_image }}
          ports:
            - containerPort: 80
          # envFrom:    #!  This is the secret that we created in goodexampleofsecretyaml
          # - secretRef:
          #     name: mysql-secret
          # - configMapRef:
          #     name: mysql-cm
          env:
            - name: MYSQL_DATABASE_HOST
              value: "mysql-service"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              value: "phonebook"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
---
apiVersion: v1
kind: Service
metadata:
  name: result-server-service
spec:
  selector:
    app: result-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30003
  type: NodePort
